/*
 * LoginPanel.java
 *
 * Created on April 19, 2007, 6:09 PM
 */

package cx.ath.feck.jchat.old.client.gui;

import cx.ath.feck.jchat.client.ClientCore;
import cx.ath.feck.jchat.old.client.Singletons;
import javax.swing.JCheckBox;

/**
 * Form for logging in, first panel displayed. Depends on a ClientCore object
 * @author john
 */
public class LoginPanel extends javax.swing.JPanel {
	
	/**
	 * Creates new form LoginPanel. Set ClientCore before using any other methods.
	 */
	public LoginPanel() {
		clientCore = Singletons.getClientCore();
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        passwordInputField = new javax.swing.JPasswordField();
        passwordInputField.setVisible(false);
        usernameInputField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordInputFieldLabel = new javax.swing.JLabel();
        passwordInputFieldLabel.setVisible(false);
        adminCheckBox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 200));
        passwordInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputFieldActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(passwordInputField, gridBagConstraints);

        usernameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputFieldActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(usernameInputField, gridBagConstraints);

        jLabel1.setText("Username");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(jLabel1, gridBagConstraints);

        passwordInputFieldLabel.setText("Password");
        passwordInputFieldLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(passwordInputFieldLabel, gridBagConstraints);

        adminCheckBox.setText("W/ Admin Privs?");
        adminCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        adminCheckBox.setContentAreaFilled(false);
        adminCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        add(adminCheckBox, gridBagConstraints);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        add(loginButton, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
	
	private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
		if(((JCheckBox)evt.getSource()).isSelected()){
			passwordInputField.setVisible(true);
			passwordInputFieldLabel.setVisible(true);
		}else{
			passwordInputField.setVisible(false);
			passwordInputFieldLabel.setVisible(false);
		}
	}//GEN-LAST:event_adminCheckBoxActionPerformed
	
	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		if(adminCheckBox.isSelected()){
			clientCore.login(usernameInputField.getText(),new String(passwordInputField.getPassword()));
		}else{
			clientCore.login(usernameInputField.getText(),null);
		}
	}//GEN-LAST:event_loginButtonActionPerformed
	
	private void passwordInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputFieldActionPerformed
		clientCore.login(usernameInputField.getText(),new String(passwordInputField.getPassword()));
	}//GEN-LAST:event_passwordInputFieldActionPerformed
	
	private void usernameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputFieldActionPerformed
		if(adminCheckBox.isSelected()){
			passwordInputField.requestFocusInWindow();
		}else{
			clientCore.login(usernameInputField.getText(),null);
		}
	}//GEN-LAST:event_usernameInputFieldActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordInputField;
    private javax.swing.JLabel passwordInputFieldLabel;
    private javax.swing.JTextField usernameInputField;
    // End of variables declaration//GEN-END:variables
	
	private ClientCore clientCore;

	
	
}
