/*
 * LoginConfirmPanel.java
 *
 * Created on April 20, 2007, 9:29 PM
 */

package cx.ath.feck.jchat.old.client.gui;



import cx.ath.feck.jchat.shared.ControlMessage;
import cx.ath.feck.jchat.shared.Status;
import cx.ath.feck.jchat.old.client.Singletons;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Displays login status info. Depends on a BasePanel
 * @author  john
 */
public class StatusPanel extends JPanel {
	
	/**
	 * Creates new form LoginConfirmPanel. Set BasePanel before calling other methods.
	 */
	public StatusPanel() {
		initComponents();
		setStatus(-1);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
        private void initComponents() {
                GridBagConstraints gridBagConstraints;

                jLabel1 = new JLabel();
                jButton1 = new JButton();

                setLayout(new GridBagLayout());

                add(jLabel1, new GridBagConstraints());

                jButton1.setText("OK");
                jButton1.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                gridBagConstraints = new GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                add(jButton1, gridBagConstraints);

        }// </editor-fold>//GEN-END:initComponents
		
	private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		Singletons.getBasePanel().setState(BasePanel.LOGIN );
	}//GEN-LAST:event_jButton1ActionPerformed
	
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private JButton jButton1;
        private JLabel jLabel1;
        // End of variables declaration//GEN-END:variables
		
		
		/**
		 * Sets status message on the panel. Use constants from ControlMessage.LoginConfirmConsts as parameter
		 * @param type Type of status to display.
		 */
		public void setStatus(int type){
			switch(type){
						default:
			case Status.LOGGINGIN:
			case Status.SUCCESS:
			case Status.SUCCESSWITHADMIN:
				jLabel1.setText("Please wait, logging in...");
				StatusPanel.this.jButton1.setVisible(false);
				break;
			case Status.FAILINVALID:
				jLabel1.setText("Failed to login, invalid or duplicate username, please choose another username.");
				StatusPanel.this.jButton1.setVisible(true);
				break;
			case Status.FAILGAINADMIN:
				jLabel1.setText("Failed to login, invalid admin password, please retry.");
				StatusPanel.this.jButton1.setVisible(true);
				break;
			case Status.FAILCONNECT:
				jLabel1.setText("Failed to connect to server");
				StatusPanel.this.jButton1.setVisible(false);
				break;
			}
			StatusPanel.this.validate();
			
		}
		
}
